name: 'Deploy AWS Lambda function via S3 Upload'
description: 'Updating a function with more than 50MB is only possible through s3.'
author: 'Yves Gurcan'
branding:
  icon: 'layers'
  color: 'orange'
inputs:
  package:
    description: 'Zip package of Lambda and dependencies'
    default: ''
  function-name:
    description: 'Name of Lambda function'
    default: ''
  s3:
    description: 'S3 key'
    default: ''
  AWS_SECRET_KEY:
    description: 'AWS secret key'
    default: ''
  AWS_SECRET_ID:
    description: 'AWS secret key ID'
    default: ''
  AWS_REGION:
    description: 'AWS region of the Lambda'
    default: ''
runs:
  using: 'node12'
  main: 'index.js'
